version: '3.5'

services:
  tutorial:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - ./tutorial:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
